from flask_wtf import Form
from wtforms import StringField, IntegerField, SubmitField, HiddenField, SelectField
from wtforms import validators
from wtforms.validators import DataRequired
from werkzeug.datastructures import MultiDict

class InputForm(Form):
    Name = StringField('User',render_kw={"size":"116"}) 
    Email = StringField('Email',render_kw={"size":"116"}) 
    Password = StringField('Password',render_kw={"size":"116"}) 
    A1 = SelectField('A.1 (Responsive Web Design ) Basic HTML and HTML5', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A2 = SelectField('A.2 (Responsive Web Design ) Basic CSS', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A3 = SelectField('A.3 (Responsive Web Design ) Applied Visual Design', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A4 = SelectField('A.4 (Responsive Web Design ) Applied Accessibility', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A5 = SelectField('A.5 (Responsive Web Design ) Responsive Web Design Principles', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A6 = SelectField('A.6 (Responsive Web Design ) CSS Flexbox', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A7 = SelectField('A.7 (Responsive Web Design ) CSS Grid', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A8 = SelectField('A.8 (Responsive Web Design ) Responsive Web Design Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B1 = SelectField('B.1 (Javascript Algorithms And Data Structures ) Basic JavaScript', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B2 = SelectField('B.2 (Javascript Algorithms And Data Structures ) ES6', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B3 = SelectField('B.3 (Javascript Algorithms And Data Structures ) Regular Expressions', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B4 = SelectField('B.4 (Javascript Algorithms And Data Structures ) Debugging', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B5 = SelectField('B.5 (Javascript Algorithms And Data Structures ) Basic Data Structures', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B6 = SelectField('B.6 (Javascript Algorithms And Data Structures ) Basic Algorithm Scripting', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B7 = SelectField('B.7 (Javascript Algorithms And Data Structures ) Object Oriented Programming', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B8 = SelectField('B.8 (Javascript Algorithms And Data Structures ) Functional Programming', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B9 = SelectField('B.9 (Javascript Algorithms And Data Structures ) Intermediate Algorithm Scripting', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B10 = SelectField('B.10 (Javascript Algorithms And Data Structures ) JavaScript Algorithms and Data Structures Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C1 = SelectField('C.1 (Front End Libraries ) Bootstrap', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C2 = SelectField('C.2 (Front End Libraries ) jQuery', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C3 = SelectField('C.3 (Front End Libraries ) Sass', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C4 = SelectField('C.4 (Front End Libraries ) React', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C5 = SelectField('C.5 (Front End Libraries ) Redux', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C6 = SelectField('C.6 (Front End Libraries ) React and Redux', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C7 = SelectField('C.7 (Front End Libraries ) Front End Libraries Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    D1 = SelectField('D.1 (Data Visualization ) Data Visualization with D3', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    D2 = SelectField('D.2 (Data Visualization ) JSON APIs and Ajax', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    D3 = SelectField('D.3 (Data Visualization ) Data Visualization Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    E1 = SelectField('E.1 (Apis And Microservices ) Managing Packages with Npm', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    E2 = SelectField('E.2 (Apis And Microservices ) Basic Node and Express', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    E3 = SelectField('E.3 (Apis And Microservices ) MongoDB and Mongoose', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    E4 = SelectField('E.4 (Apis And Microservices ) Apis and Microservices Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    F1 = SelectField('F.1 (Information Security And Quality Assurance ) Information Security with HelmetJS', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    F2 = SelectField('F.2 (Information Security And Quality Assurance ) Quality Assurance and Testing with Chai', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    F3 = SelectField('F.3 (Information Security And Quality Assurance ) Advanced Node and Express', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    F4 = SelectField('F.4 (Information Security And Quality Assurance ) Information Security and Quality Assurance Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    G1 = SelectField('G.1 (Coding Interview Prep ) Algorithms', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    G2 = SelectField('G.2 (Coding Interview Prep ) Data Structures', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    G3 = SelectField('G.3 (Coding Interview Prep ) Take Home Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    G4 = SelectField('G.4 (Coding Interview Prep ) Rosetta Code', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    G5 = SelectField('G.5 (Coding Interview Prep ) Project Euler', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    Save = SubmitField('Save',render_kw={"size":"500"})

class LoginForm(Form):
    LoginEmail = StringField('Email',render_kw={"placeholder":"Email","size":"85"}) 
    LoginPassword = StringField('Password',render_kw={"placeholder":"Password","size":"85"}) 
    LoginButton = SubmitField('Login',render_kw={"size":"500"})

class RegisterForm(Form):
    RegisterEmail = StringField('Email',render_kw={"placeholder":"Email","size":"85"}) 
    RegisterPassword = StringField('Password',render_kw={"placeholder":"Password (Optional)","size":"85"}) 
    RegisterButton = SubmitField('Register',render_kw={"size":"500"})

class VueInputForm(Form):
    Name = StringField('User',render_kw={"size":"116"}) 
    Email = StringField('Email',render_kw={"size":"116"}) 
    Password = StringField('Password',render_kw={"size":"116"}) 
    A1 = SelectField('1 (JavaScript Algorithms And Data Structures) Basic JavaScript', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A2 = SelectField('2 (JavaScript Algorithms And Data Structures) ES6', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A3 = SelectField('3 (JavaScript Algorithms And Data Structures) Regular Expressions', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A4 = SelectField('4 (JavaScript Algorithms And Data Structures) Debugging', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A5 = SelectField('5 (JavaScript Algorithms And Data Structures) Basic Data Structures', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A6 = SelectField('6 (JavaScript Algorithms And Data Structures) Basic Algorithm Scripting', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A7 = SelectField('7 (JavaScript Algorithms And Data Structures) Object Oriented Programming', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A8 = SelectField('8 (JavaScript Algorithms And Data Structures) Functional Programming', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A9 = SelectField('9 (JavaScript Algorithms And Data Structures) Intermediate Algorithm Scripting', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A10 = SelectField('10 (JavaScript Algorithms And Data Structures) JavaScript Algorithms and Data Structures Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B1 = SelectField('1 (JavaScript 30) JavaScript Drum Kit', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B2 = SelectField('2 (JavaScript 30) CSS + JS Clock', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B3 = SelectField('3 (JavaScript 30) Playing with CSS Variables and JS', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B4 = SelectField('4 (JavaScript 30) Array Cardio 1', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B5 = SelectField('5 (JavaScript 30) Flex Panels Image Gallery', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B6 = SelectField('6 (JavaScript 30) AJAX Type Ahead', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B7 = SelectField('7 (JavaScript 30) Array Cardio 2', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B8 = SelectField('8 (JavaScript 30) Fun with HTML5 Canvas', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B9 = SelectField('9 (JavaScript 30) 14 Must Know Dev Tool Tricks', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B10 = SelectField('10 (JavaScript 30) Hold Shift to check multiple checkboxes', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B11 = SelectField('11 (JavaScript 30) Custom HTML5 Video Player', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B12 = SelectField('12 (JavaScript 30) Key Sequence Detection (Konami Code)', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B13 = SelectField('13 (JavaScript 30) Slide in on scroll', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B14 = SelectField('14 (JavaScript 30) Objects and Arrays - Reference vs Copy', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B15 = SelectField('15 (JavaScript 30) Localstorage and Event Delegation', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B16 = SelectField('16 (JavaScript 30) CSS Text Shadow mouse move effect', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B17 = SelectField('17 (JavaScript 30) Sorting band names without articles', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B18 = SelectField('18 (JavaScript 30) Tally string times with reduce', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B19 = SelectField('19 (JavaScript 30) Unreal webcam fun', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B20 = SelectField('20 (JavaScript 30) Native speech recognition', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B21 = SelectField('21 (JavaScript 30) Geolocation based Speedometer and Compass', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B22 = SelectField('22 (JavaScript 30) Follow along links', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B23 = SelectField('23 (JavaScript 30) Speech synthesis', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B24 = SelectField('24 (JavaScript 30) Sticky Nav', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B25 = SelectField('25 (JavaScript 30) Event capture, propagation, bubbling and once', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B26 = SelectField('26 (JavaScript 30) Stripe follow along dropdown', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B27 = SelectField('27 (JavaScript 30) Click and drag to scroll', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B28 = SelectField('28 (JavaScript 30) Video speed controller UI', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B29 = SelectField('29 (JavaScript 30) Countdown clock', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    B30 = SelectField('30 (JavaScript 30) Whack a mole game', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C1 = SelectField('1 (Responsive Web Design) Basic HTML and HTML5', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C2 = SelectField('2 (Responsive Web Design) Basic CSS', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C3 = SelectField('3 (Responsive Web Design) Applied Visual Design', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C4 = SelectField('4 (Responsive Web Design) Applied Accessibility', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C5 = SelectField('5 (Responsive Web Design) Responsive Web Design Principles', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C6 = SelectField('6 (Responsive Web Design) CSS Flexbox', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C7 = SelectField('7 (Responsive Web Design) CSS Grid', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    C8 = SelectField('8 (Responsive Web Design) Responsive Web Design Projects', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    Save = SubmitField('Save',render_kw={"size":"500"})

class ReactInputForm(Form):
    Name = StringField('User',render_kw={"size":"116"}) 
    Email = StringField('Email',render_kw={"size":"116"}) 
    Password = StringField('Password',render_kw={"size":"116"}) 
    A1 = SelectField('[Foundations] 1. How this Course Will Work', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A2 = SelectField('[Foundations] 2. Introduction to Web Development', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A3 = SelectField('[Foundations] 3. Motivation and Mindset', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A4 = SelectField('[Foundations] 4. Asking For Help', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A5 = SelectField('[Foundations] 5. Join the Odin Community', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A6 = SelectField('[Foundations] 6. How Does the Web Work?', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A7 = SelectField('[Installations] 1. Installation Overview', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A8 = SelectField('[Installations] 2. Prerequisites', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A9 = SelectField('[Installations] 3. Text Editors', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A10 = SelectField('[Installations] 4. Command Line Basics', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A11 = SelectField('[Installations] 5. Setting Up Git', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A12 = SelectField('[Git Basics] 1. Introduction to Git', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A13 = SelectField('[Git Basics]2. Git Basics', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A14 = SelectField('[HTML Foundations] 1. Introduction to HTML and CSS', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A15 = SelectField('[HTML Foundations] 2. Elements and Tags', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A16 = SelectField('[HTML Foundations] 3. HTML Boilerplate', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A17 = SelectField('[HTML Foundations] 4. Working with Text', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A18 = SelectField('[HTML Foundations] 5. Lists', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A19 = SelectField('[HTML Foundations] 6. Links and Images', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A20 = SelectField('[HTML Foundations] 7. Commit Messages', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A21 = SelectField('[HTML Foundations] 8. Project: Recipes', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A22 = SelectField('[CSS Foundations] 1. CSS Foundations', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A23 = SelectField('[CSS Foundations] 2. Inspecting HTML and CSS', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A24 = SelectField('[CSS Foundations] 3. The Box Model', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A25 = SelectField('[CSS Foundations] 4. Block and Inline', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A26 = SelectField('[Flexbox] 1. Introduction to Flexbox', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A27 = SelectField('[Flexbox] 2. Growing and Shrinking', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A28 = SelectField('[Flexbox] 3. Axes', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A29 = SelectField('[Flexbox] 4. Alignment', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A30 = SelectField('[Flexbox] 5. Project: Landing Page', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A31 = SelectField('[JavaScript Basics] 1. Fundamentals Part 1', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A32 = SelectField('[JavaScript Basics] 2. Fundamentals Part 2', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A33 = SelectField('[JavaScript Basics] 3. JavaScript Developer Tools', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])        
    A34 = SelectField('[JavaScript Basics] 4. Fundamentals Part 3', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A35 = SelectField('[JavaScript Basics] 5. Problem Solving', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A36 = SelectField('[JavaScript Basics] 6. Understanding Errors', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])        
    A37 = SelectField('[JavaScript Basics] 7. Project: Rock Paper Scissors', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])
    A38 = SelectField('[JavaScript Basics] 8. Clean Code', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])        
    A39 = SelectField('[JavaScript Basics] 9. Installing Node.js', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])            
    A40 = SelectField('[JavaScript Basics] 10. Fundamentals Part 4', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])            
    A41 = SelectField('[JavaScript Basics] 11. DOM Manipulation and Events', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])            
    A42 = SelectField('[JavaScript Basics] 12. Revisiting Rock Paper Scissors', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])            
    A43 = SelectField('[JavaScript Basics] 13. Project: Etch-a-Sketch', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])            
    A44 = SelectField('[JavaScript Basics] 14. Fundamentals Part 5', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])            
    A45 = SelectField('[JavaScript Basics] 15. Project: Calculator', choices=[('Not yet started','Not yet started'),('In progress','In progress'),('Completed','Completed')])            
    Save = SubmitField('Save',render_kw={"size":"500"})    